backend:
  name: github
  repo: JLT042/portfolio-starter-kit
  branch: main
  base_url: https://jlt-cms-bridge.vercel.app

media_folder: "public/images/logos"
public_folder: "/images/logos"

# Aktiviert Mehrsprachigkeit
i18n:
  structure: single_file
  locales: [de, en, es]
  default_locale: de

collections:
  - name: "pages"
    label: "Seiten Inhalte"
    folder: "public/content/pages" # Wir speichern es als JSON im public Ordner
    extension: "json"
    format: "json"
    create: true
    i18n: true
    files:
      - label: "Startseite"
        name: "home"
        file: "public/content/pages/home.json"
        i18n: true
        fields:
          - { label: "Hero Headline", name: "hero_headline", widget: "string", i18n: true }
          - { label: "Hero Subtext", name: "hero_sub", widget: "text", i18n: true }
          - { label: "Nav Projekt Link", name: "nav_projects", widget: "string", i18n: true }
          - { label: "Nav Service Link", name: "nav_services", widget: "string", i18n: true }
          - { label: "Nav Kontakt Link", name: "nav_contact", widget: "string", i18n: true }
          - { label: "Button Text", name: "nav_cta", widget: "string", i18n: true }
